Added env.yaml for Conda environment
ufs-community/workflow-tools pull request #16
Opened 2022-02-25 19:25 UTC by ope-adejumo

**Description**

**Type of change**

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

**Checklist**

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation.  I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

2022-02-25 19:37 UTC, aerorahul requested changes
I believe the file `environment.yml` should be at the `root` directory level.
Other than that, it looks good to me.

2022-02-28 16:01 UTC, christinaholtNOAA requested changes
I agree with @aerorahul about the location of the file.

2022-03-04 16:06 UTC, fgabelmannjr approved these changes

2022-03-04 16:06 UTC, christinaholtNOAA approved these changes

2022-03-04 16:06 UTC, merged