add basic setup and directory structure
ufs-community/workflow-tools pull request #2
Opened 2022-01-31 17:51 UTC by aerorahul

This PR:
- adds a very basic `setup.py` and `setup.cfg` skeleton
- adds a very basic directory structure for source code and tests and possibly documentation (when it arrives)

2022-02-02 17:19 UTC, christinaholtNOAA requested changes
This duplicates many of the files in PR #3 and should probably be closed so we can focus on that one?

2022-02-02 17:40 UTC, aerorahul commented
> This duplicates many of the files in PR #3 and should probably be closed so we can focus on that one?

This PR was issued before #3.
The duplicates in #3 will be automatically resolved once #2 is merged.

2022-02-02 17:44 UTC, christinaholtNOAA commented
Welp, I ended up leaving comments on these files in PR #3.

2022-02-03 04:46 UTC, aerorahul commented
closing this PR because it #3 contains discussion related to commits from this PR.

2022-02-03 04:46 UTC, closed without merging