Break codeowners for reviewing.
ufs-community/workflow-tools pull request #60
Opened 2022-05-09 17:23 UTC by aerorahul

This draft PR just adds reviewers following Github documentation.

2022-05-09 17:40 UTC, christinaholtNOAA approved these changes

2022-05-18 15:37 UTC, christinaholtNOAA requested changes

2022-05-23 17:50 UTC, ryanlong1004 commented on .github/CODEOWNERS
> +*.py    @aerorahul @ryanlong1004 @ope-adejumo
done.

2022-05-23 18:20 UTC, christinaholtNOAA approved these changes

2022-05-23 18:23 UTC, merged