update tests
ufs-community/workflow-tools pull request #82
Opened 2022-06-01 19:35 UTC by ryanlong1004

Tests the 'print job card' functionality.

2022-06-01 20:54 UTC, christinaholtNOAA requested changes
Looks good.

2022-06-01 20:54 UTC, christinaholtNOAA commented on tests/test_scheduler.py
> +    print(jc)
I assume that we want to expect that `__str__` is actually returning a string, and don't want to hide that potential oversight (an inadvertent change to the `__str__` method) in the `str()` on line 472. Could it just be:
```
actual = js.job_card
assert actual == expected
```

Also, would it be okay to remove the `print()`?

2022-06-16 15:08 UTC, aerorahul commented
waiting on resolution from @christinaholtNOAA's comment.
And then we can close/merge this.

2022-06-22 18:47 UTC, aerorahul commented on tests/test_scheduler.py
> +    print(jc)
```suggestion
```

2022-06-22 18:47 UTC, aerorahul approved these changes
looks good.

2022-06-27 19:58 UTC, ryanlong1004 commented
@christinaholtNOAA bump

2022-06-27 21:46 UTC, merged